
languageCode = 'en-us'
title = 'vdtlv portfolio'
theme = 'pehtheme-hugo'

# paginate = '6' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Pehtheme Hugo Lite: A minimalist Hugo theme, built with TailwindCSS, for efficient performance and minimalism.'
	mainSections = ''

[author]
	name = 'vdtlv'
	bio = 'Debitis assumenda esse dignissimos aperiam delectus maxime tenetur repudiandae dolore'
	avatar = '/images/nasa-astronaut-unsplash.jpg'
	twitter = 'https://twitter.com/insertapps'

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'About'
		pageRef = '/about'
		weight = 15
	[[menu.main]]
		name = 'Tags'
		pageRef = '/tags'
		weight = 20
	[[menus.main]]
		name = 'vdtlv.me'
		pageRef = 'https://vdtlv.me'
		weight = 30

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'